// Liste tüm ISO ülke kodlarını, isimlerini ve emoji bayraklarını içerir
// Emoji bayraklar, ülke kodu kullanılarak oluşturulmuştur (ISO 3166-1 alpha-2)

interface Country {
  code: string;
  name: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "TR", name: "Türkiye", flag: "🇹🇷" },
  { code: "AD", name: "Andorra", flag: "🇦🇩" },
  { code: "AE", name: "Birleşik Arap Emirlikleri", flag: "🇦🇪" },
  { code: "AF", name: "Afganistan", flag: "🇦🇫" },
  { code: "AG", name: "Antigua ve Barbuda", flag: "🇦🇬" },
  { code: "AL", name: "Arnavutluk", flag: "🇦🇱" },
  { code: "AM", name: "Ermenistan", flag: "🇦🇲" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "AR", name: "Arjantin", flag: "🇦🇷" },
  { code: "AT", name: "Avusturya", flag: "🇦🇹" },
  { code: "AU", name: "Avustralya", flag: "🇦🇺" },
  { code: "AZ", name: "Azerbaycan", flag: "🇦🇿" },
  { code: "BA", name: "Bosna Hersek", flag: "🇧🇦" },
  { code: "BB", name: "Barbados", flag: "🇧🇧" },
  { code: "BD", name: "Bangladeş", flag: "🇧🇩" },
  { code: "BE", name: "Belçika", flag: "🇧🇪" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BG", name: "Bulgaristan", flag: "🇧🇬" },
  { code: "BH", name: "Bahreyn", flag: "🇧🇭" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "BJ", name: "Benin", flag: "🇧🇯" },
  { code: "BN", name: "Brunei", flag: "🇧🇳" },
  { code: "BO", name: "Bolivya", flag: "🇧🇴" },
  { code: "BR", name: "Brezilya", flag: "🇧🇷" },
  { code: "BS", name: "Bahamalar", flag: "🇧🇸" },
  { code: "BT", name: "Butan", flag: "🇧🇹" },
  { code: "BW", name: "Botsvana", flag: "🇧🇼" },
  { code: "BY", name: "Belarus", flag: "🇧🇾" },
  { code: "BZ", name: "Belize", flag: "🇧🇿" },
  { code: "CA", name: "Kanada", flag: "🇨🇦" },
  { code: "CD", name: "Demokratik Kongo Cumhuriyeti", flag: "🇨🇩" },
  { code: "CF", name: "Orta Afrika Cumhuriyeti", flag: "🇨🇫" },
  { code: "CG", name: "Kongo Cumhuriyeti", flag: "🇨🇬" },
  { code: "CH", name: "İsviçre", flag: "🇨🇭" },
  { code: "CI", name: "Fildişi Sahili", flag: "🇨🇮" },
  { code: "CL", name: "Şili", flag: "🇨🇱" },
  { code: "CM", name: "Kamerun", flag: "🇨🇲" },
  { code: "CN", name: "Çin", flag: "🇨🇳" },
  { code: "CO", name: "Kolombiya", flag: "🇨🇴" },
  { code: "CR", name: "Kosta Rika", flag: "🇨🇷" },
  { code: "CU", name: "Küba", flag: "🇨🇺" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "CY", name: "Kıbrıs", flag: "🇨🇾" },
  { code: "CZ", name: "Çekya", flag: "🇨🇿" },
  { code: "DE", name: "Almanya", flag: "🇩🇪" },
  { code: "DJ", name: "Cibuti", flag: "🇩🇯" },
  { code: "DK", name: "Danimarka", flag: "🇩🇰" },
  { code: "DM", name: "Dominika", flag: "🇩🇲" },
  { code: "DO", name: "Dominik Cumhuriyeti", flag: "🇩🇴" },
  { code: "DZ", name: "Cezayir", flag: "🇩🇿" },
  { code: "EC", name: "Ekvador", flag: "🇪🇨" },
  { code: "EE", name: "Estonya", flag: "🇪🇪" },
  { code: "EG", name: "Mısır", flag: "🇪🇬" },
  { code: "ER", name: "Eritre", flag: "🇪🇷" },
  { code: "ES", name: "İspanya", flag: "🇪🇸" },
  { code: "ET", name: "Etiyopya", flag: "🇪🇹" },
  { code: "FI", name: "Finlandiya", flag: "🇫🇮" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯" },
  { code: "FM", name: "Mikronezya", flag: "🇫🇲" },
  { code: "FR", name: "Fransa", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "GB", name: "Birleşik Krallık", flag: "🇬🇧" },
  { code: "GD", name: "Grenada", flag: "🇬🇩" },
  { code: "GE", name: "Gürcistan", flag: "🇬🇪" },
  { code: "GH", name: "Gana", flag: "🇬🇭" },
  { code: "GM", name: "Gambiya", flag: "🇬🇲" },
  { code: "GN", name: "Gine", flag: "🇬🇳" },
  { code: "GQ", name: "Ekvator Ginesi", flag: "🇬🇶" },
  { code: "GR", name: "Yunanistan", flag: "🇬🇷" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "GW", name: "Gine-Bissau", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "HR", name: "Hırvatistan", flag: "🇭🇷" },
  { code: "HT", name: "Haiti", flag: "🇭🇹" },
  { code: "HU", name: "Macaristan", flag: "🇭🇺" },
  { code: "ID", name: "Endonezya", flag: "🇮🇩" },
  { code: "IE", name: "İrlanda", flag: "🇮🇪" },
  { code: "IL", name: "İsrail", flag: "🇮🇱" },
  { code: "IN", name: "Hindistan", flag: "🇮🇳" },
  { code: "IQ", name: "Irak", flag: "🇮🇶" },
  { code: "IR", name: "İran", flag: "🇮🇷" },
  { code: "IS", name: "İzlanda", flag: "🇮🇸" },
  { code: "IT", name: "İtalya", flag: "🇮🇹" },
  { code: "JM", name: "Jamaika", flag: "🇯🇲" },
  { code: "JO", name: "Ürdün", flag: "🇯🇴" },
  { code: "JP", name: "Japonya", flag: "🇯🇵" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "KG", name: "Kırgızistan", flag: "🇰🇬" },
  { code: "KH", name: "Kamboçya", flag: "🇰🇭" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮" },
  { code: "KM", name: "Komorlar", flag: "🇰🇲" },
  { code: "KN", name: "Saint Kitts ve Nevis", flag: "🇰🇳" },
  { code: "KP", name: "Kuzey Kore", flag: "🇰🇵" },
  { code: "KR", name: "Güney Kore", flag: "🇰🇷" },
  { code: "KW", name: "Kuveyt", flag: "🇰🇼" },
  { code: "KZ", name: "Kazakistan", flag: "🇰🇿" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "LB", name: "Lübnan", flag: "🇱🇧" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "LR", name: "Liberya", flag: "🇱🇷" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "LT", name: "Litvanya", flag: "🇱🇹" },
  { code: "LU", name: "Lüksemburg", flag: "🇱🇺" },
  { code: "LV", name: "Letonya", flag: "🇱🇻" },
  { code: "LY", name: "Libya", flag: "🇱🇾" },
  { code: "MA", name: "Fas", flag: "🇲🇦" },
  { code: "MC", name: "Monako", flag: "🇲🇨" },
  { code: "MD", name: "Moldova", flag: "🇲🇩" },
  { code: "ME", name: "Karadağ", flag: "🇲🇪" },
  { code: "MG", name: "Madagaskar", flag: "🇲🇬" },
  { code: "MH", name: "Marshall Adaları", flag: "🇲🇭" },
  { code: "MK", name: "Kuzey Makedonya", flag: "🇲🇰" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "MN", name: "Moğolistan", flag: "🇲🇳" },
  { code: "MR", name: "Moritanya", flag: "🇲🇷" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  { code: "MV", name: "Maldivler", flag: "🇲🇻" },
  { code: "MW", name: "Malavi", flag: "🇲🇼" },
  { code: "MX", name: "Meksika", flag: "🇲🇽" },
  { code: "MY", name: "Malezya", flag: "🇲🇾" },
  { code: "MZ", name: "Mozambik", flag: "🇲🇿" },
  { code: "NA", name: "Namibya", flag: "🇳🇦" },
  { code: "NE", name: "Nijer", flag: "🇳🇪" },
  { code: "NG", name: "Nijerya", flag: "🇳🇬" },
  { code: "NI", name: "Nikaragua", flag: "🇳🇮" },
  { code: "NL", name: "Hollanda", flag: "🇳🇱" },
  { code: "NO", name: "Norveç", flag: "🇳🇴" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "NR", name: "Nauru", flag: "🇳🇷" },
  { code: "NZ", name: "Yeni Zelanda", flag: "🇳🇿" },
  { code: "OM", name: "Umman", flag: "🇴🇲" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "PG", name: "Papua Yeni Gine", flag: "🇵🇬" },
  { code: "PH", name: "Filipinler", flag: "🇵🇭" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "PL", name: "Polonya", flag: "🇵🇱" },
  { code: "PT", name: "Portekiz", flag: "🇵🇹" },
  { code: "PW", name: "Palau", flag: "🇵🇼" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "QA", name: "Katar", flag: "🇶🇦" },
  { code: "RO", name: "Romanya", flag: "🇷🇴" },
  { code: "RS", name: "Sırbistan", flag: "🇷🇸" },
  { code: "RU", name: "Rusya", flag: "🇷🇺" },
  { code: "RW", name: "Ruanda", flag: "🇷🇼" },
  { code: "SA", name: "Suudi Arabistan", flag: "🇸🇦" },
  { code: "SB", name: "Solomon Adaları", flag: "🇸🇧" },
  { code: "SC", name: "Seyşeller", flag: "🇸🇨" },
  { code: "SD", name: "Sudan", flag: "🇸🇩" },
  { code: "SE", name: "İsveç", flag: "🇸🇪" },
  { code: "SG", name: "Singapur", flag: "🇸🇬" },
  { code: "SI", name: "Slovenya", flag: "🇸🇮" },
  { code: "SK", name: "Slovakya", flag: "🇸🇰" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "SM", name: "San Marino", flag: "🇸🇲" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "SO", name: "Somali", flag: "🇸🇴" },
  { code: "SR", name: "Surinam", flag: "🇸🇷" },
  { code: "SS", name: "Güney Sudan", flag: "🇸🇸" },
  { code: "ST", name: "Sao Tome ve Principe", flag: "🇸🇹" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "SY", name: "Suriye", flag: "🇸🇾" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "TD", name: "Çad", flag: "🇹🇩" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "TH", name: "Tayland", flag: "🇹🇭" },
  { code: "TJ", name: "Tacikistan", flag: "🇹🇯" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "TM", name: "Türkmenistan", flag: "🇹🇲" },
  { code: "TN", name: "Tunus", flag: "🇹🇳" },
  { code: "TO", name: "Tonga", flag: "🇹🇴" },
  { code: "TR", name: "Türkiye", flag: "🇹🇷" },
  { code: "TT", name: "Trinidad ve Tobago", flag: "🇹🇹" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻" },
  { code: "TW", name: "Tayvan", flag: "🇹🇼" },
  { code: "TZ", name: "Tanzanya", flag: "🇹🇿" },
  { code: "UA", name: "Ukrayna", flag: "🇺🇦" },
  { code: "UG", name: "Uganda", flag: "🇺🇬" },
  { code: "US", name: "Amerika Birleşik Devletleri", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", name: "Özbekistan", flag: "🇺🇿" },
  { code: "VA", name: "Vatikan", flag: "🇻🇦" },
  { code: "VC", name: "Saint Vincent ve Grenadinler", flag: "🇻🇨" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺" },
  { code: "WS", name: "Samoa", flag: "🇼🇸" },
  { code: "YE", name: "Yemen", flag: "🇾🇪" },
  { code: "ZA", name: "Güney Afrika", flag: "🇿🇦" },
  { code: "ZM", name: "Zambiya", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabve", flag: "🇿🇼" },
];

// Yeni verileri veritabanı şemasına eklemek için:
export const countriesSchema = countries.map(country => ({
  code: country.code,
  name: country.name,
  flag: country.flag,
  isActive: true
}));

// Ülkeleri alfabetik sırala
export const sortedCountries = [...countries].sort((a, b) => a.name.localeCompare(b.name, 'tr'));

// Kod ile ülke bilgilerini bul
export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

// ISO iki harfli kodu kullanarak bayrak emoji oluştur
export const getFlagEmoji = (countryCode: string) => {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char =>  127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};